OUTPUT_DIR: "exp/1210-cuhk2prw1"
INPUT:
  DATASET: "CUHK-SYSU"
  TDATASET: "PRW"
  DATA_ROOT: "/mnt/nfs/data/home/1120210297/CUHK-SYSU"
  TDATA_ROOT: "/mnt/nfs/data/home/1120210297/PRW"
  BATCH_SIZE_TRAIN: 8
SOLVER:
  MAX_EPOCHS: 6
  LR_DECAY_MILESTONES: [16]
  BASE_LR: 0.00002
  LW_DA_INS: 0.98
MODEL:
  LOSS:
    LUT_SIZE: 6015
    CQ_SIZE: 5000
EVAL_PERIOD: 1
TARGET_REID_START: 0
EPS_P: 0.98
