OUTPUT_DIR: "exp"
INPUT:
  DATASET: "CUHK-SYSU"
  TDATASET: "PRW"
  DATA_ROOT: "/mnt/nfs/data/home//CUHK-SYSU"
  TDATA_ROOT: "/mnt/nfs/data/home//PRW"
  BATCH_SIZE_TRAIN: 4
SOLVER:
  MAX_EPOCHS: 6
  LR_DECAY_MILESTONES: [16]
  BASE_LR: 0.004
  LW_DA_INS: 0.98
MODEL:
  LOSS:
    LUT_SIZE: 6015
    CQ_SIZE: 5000
EVAL_PERIOD: 2
TARGET_REID_START: 10
EPS_P: 0.98
