OUTPUT_DIR: "exp"
INPUT:
  TDATASET: "CUHK-SYSU"
  DATASET: "PRW"
  TDATA_ROOT: "/path/to/CUHK-SYSU"
  DATA_ROOT: "/path/to/PRW"
  BATCH_SIZE_TRAIN: 4
SOLVER:
  MAX_EPOCHS: 20
  BASE_LR: 0.003
  LW_BOX_REID_T: 0.5
MODEL:
  LOSS:
    LUT_SIZE: 482
    CQ_SIZE: 500
EVAL_PERIOD: 1
TARGET_REID_START: 0
EPS_P: 0.95
HM_THRESH: 0.3