OUTPUT_DIR: "exp/20241210_cuhk"
INPUT:
  TDATASET: "CUHK-SYSU"
  DATASET: "PRW"
  TDATA_ROOT: "/mnt/nfs/data/home/1120210297/CUHK-SYSU"
  DATA_ROOT: "/mnt/nfs/data/home/1120210297/PRW"
  BATCH_SIZE_TRAIN: 8
SOLVER:
  MAX_EPOCHS: 5
  BASE_LR: 0.00005
  LW_BOX_REID_T: 0.8
MODEL:
  LOSS:
    LUT_SIZE: 482
    CQ_SIZE: 500
EVAL_PERIOD: 1
TARGET_REID_START: 0
EPS_P: 0.95
HM_THRESH: 0.3